-- CREATE DATABASE resume_db;

-- USE resume_db;

CREATE TABLE resumes (
  id INT(11) NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(100) DEFAULT NULL,
  address VARCHAR(255) DEFAULT NULL,
  mobile VARCHAR(20) DEFAULT NULL,
  email VARCHAR(100) DEFAULT NULL,
  photo VARCHAR(255) DEFAULT NULL,
  skills TEXT DEFAULT NULL,
  education TEXT DEFAULT NULL,
  experience TEXT DEFAULT NULL,
  profile TEXT DEFAULT NULL,
  projects TEXT DEFAULT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
